name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number'
        required: true
        type: string

jobs:
  Release:
    name: Release ${{ inputs.version }}
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install WASM Workload
        run: dotnet workload install wasm-tools

      #- name: Publish to NuGet
      #  uses: MrKWatkins/nuget-publish@main
      #  with:
      #    directory: src
      #    nuget-api-key: ${{ secrets.NUGET_API_KEY }}
      #    version: ${{ inputs.version }}

      - name: Build
        uses: MrKWatkins/dotnet-build@main
        with:
          name: MrKWatkins.OakIO
          directory: src

      - name: Restore .NET tools
        run: dotnet tool restore

      - name: Install Sesharp
        run: dotnet tool install MrKWatkins.Sesharp.Tool

      - name: Generate API Docs - MrKWatkins.OakIO
        run: dotnet sesharp src/MrKWatkins.OakIO/bin/Release/net10.0/MrKWatkins.OakIO.dll src/MrKWatkins.OakIO.ZXSpectrum/bin/Release/net10.0/MrKWatkins.OakIO.ZXSpectrum.dll --output doc/docs/API --repository https://github.com/MrKWatkins/OakIO

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: doc/mkdocs.yml
          REQUIREMENTS: doc/requirements.txt
